name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */8 * * *'     #
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I -L -s -o /dev/null -w "%{http_code}" https://streamlit.app
